apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: csi
      defaultBucket: metrics
    secureJsonData:
      token: csi-sensor-dev-token
    isDefault: true
